# Generated by Django 5.0.6 on 2025-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hint',
            field=models.TextField(default=''),
        ),
    ]
