# Generated by Django 5.0.6 on 2025-04-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_word_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
